<%= partial('base_image') %>

<%#LABEL io.k8s.description="Base Image for Rails and Sphinx containers" \%>
      <%#io.k8s.display-name="pitc-rails-sphinx-bi" \%>
      <%#io.openshift.expose-services="8080:http,9312:sphinx" \%>
      <%#io.openshift.tags="builder,ruby,ruby22,httpd,sphinx"%>

# ABOUT
# A Rails image.
#
# This image is based on a S2I image but used in standard 'docker build'
# fashion. This is done by triggering $STI_SCRIPTS_PATH/assemble while
# building.

<%= partial('install_sphinx') %>
<%= partial('apache_passenger_rails') %>

<%= partial('add_s2i_scripts') %>

USER 1001

<%= partial('entrypoint') %>
