<%= partial('base_image') %>

# ABOUT
# A Rails image to be used with OpenShift S2I.

<%= partial('apache_passenger_rails') %>

<%= partial('add_s2i_scripts') %>

USER 1001

<%= partial('entrypoint') %>
