<%= partial('base_image') %>

<%#LABEL io.k8s.description="Base Image for Rails and Sphinx containers including transifex client" \%>
      <%#io.k8s.display-name="pitc-rails-sphinx-transifex-bi" \%>
      <%#io.openshift.expose-services="8080:http,9312:sphinx" \%>
      <%#io.openshift.tags="builder,ruby,ruby22,httpd,sphinx"%>

# ABOUT
# A Rails image to be used with OpenShift S2I.

<%= partial('install_sphinx') %>
<%= partial('install_transifex') %>
<%= partial('apache_passenger_rails') %>

<%= partial('add_s2i_scripts') %>

USER 1001

<%= partial('entrypoint') %>
