<%= partial('base_image') %>

# ABOUT
# A Rails/webpack frontend image to be used with S2I.
#
#   * nodejs, npm and yarn will get installed
#   * the assets at frontend/dist are moved to public/

<%= partial('apache_passenger_rails') %>

USER root
# Install node.
RUN yum install -y centos-release-scl-rh && \
    INSTALL_PKGS="rh-nodejs4 rh-nodejs4-npm rh-nodejs4-nodejs-nodemon nss_wrapper" && \
    ln -s /usr/lib/node_modules/nodemon/bin/nodemon.js /usr/bin/nodemon && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y

# install yarn (install without dep check since nodejs is installed by scl)
RUN wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo && \
    rpm -Uvh --nodeps $(repoquery --location yarn)

<%= partial('add_s2i_scripts') %>

USER 1001

<%= partial('entrypoint') %>
